import asyncio
import logging
import json
import os
import signal
from datetime import datetime
from typing import Optional, Callable, Dict, Any

import blcsdk
import blcsdk.models as sdk_models

from app import config
from app.models import ParsedMessage, MessageType

logger = logging.getLogger('biliutility.sdk')

_msg_handler: Optional['MsgHandler'] = None
_loop = None


GUARD_LEVEL_NAMES = {
    sdk_models.GuardLevel.LV1: '舰长',
    sdk_models.GuardLevel.LV2: '提督',
    sdk_models.GuardLevel.LV3: '总督',
}

async def init_sdk(message_callback: Callable[[ParsedMessage], Any]):
    """Initialize the message handler with blcsdk. Must be awaited before SDK messages arrive."""
    global _msg_handler, _loop
    _loop = asyncio.get_running_loop()

    # Set the handler BEFORE init() so it's ready when BLC_INIT arrives
    _msg_handler = MsgHandler(message_callback, _loop)
    blcsdk.set_msg_handler(_msg_handler)

    # Actually connect to blivechat via WebSocket (reads BLC_PORT / BLC_TOKEN env vars)
    await blcsdk.init()
    logger.info('[SDK] SDK initialized and connected to blivechat')

    # Check SDK version compatibility (per SDK docs: exit if incompatible)
    if not blcsdk.is_sdk_version_compatible():
        logger.warning('[SDK] SDK version is NOT compatible with blivechat — plugin may not work correctly')

async def shut_down_sdk():
    """Clean up resources on shutdown: clear handler, close WebSocket & HTTP session."""
    blcsdk.set_msg_handler(None)
    await blcsdk.shut_down()
    logger.info('[SDK] SDK shut down cleanly')


# Commands that contain chat data we want to record
_CHAT_COMMANDS = {50, 51, 52, 53, 54}  # ADD_TEXT, ADD_GIFT, ADD_MEMBER, ADD_SUPER_CHAT, DEL_SUPER_CHAT



# Session start time — one filename per plugin session (matches room_{id}-{date}_{time}.jsonl pattern)
_session_start = datetime.now().strftime('%Y%m%d_%H%M%S')

def _write_raw_message(command: Dict[str, Any], room_id: Optional[int] = None):
    """
    Dump the raw blcsdk command packet to log/messages/ as JSONL, unmodified.
    Each line: {"timestamp": "...", "packet": {<raw command dict>}}

    If room_id is known, writes to:  room_{room_id}-{date}_{session}.jsonl
    Otherwise falls back to:         raw_{date}.jsonl
    """
    try:
        messages_path = getattr(config, 'BACKUP_LOG_PATH', os.path.join('log', 'messages'))
        os.makedirs(messages_path, exist_ok=True)

        today = datetime.now().strftime('%Y%m%d')
        if room_id:
            filename = f'room_{room_id}-{today}_{_session_start}.jsonl'
        else:
            filename = f'raw_{today}_{_session_start}.jsonl'

        entry = {
            'timestamp': datetime.now().isoformat(),
            'packet': command          # raw dict, zero modification
        }
        with open(os.path.join(messages_path, filename), 'a', encoding='utf-8') as f:
            f.write(json.dumps(entry, ensure_ascii=False) + '\n')
    except Exception as e:
        logger.error(f'[SDK] Failed to write raw message: {e}')

class MsgHandler(blcsdk.BaseHandler):
    def __init__(self, callback: Callable[[ParsedMessage], Any], loop: asyncio.AbstractEventLoop):
        self._callback = callback
        self._loop = loop

    def on_client_stopped(self, client: blcsdk.BlcPluginClient, exception: Optional[Exception]):
        """Called when blivechat exits or plugin is disabled. Per SDK docs, we must exit."""
        logger.info('[SDK] blivechat disconnected — shutting down plugin')
        # Signal the process to terminate gracefully
        os.kill(os.getpid(), signal.SIGINT)

    def _safe_callback(self, msg: ParsedMessage):
        """Schedule async callback on the event loop (handle() runs on the same loop)."""
        if self._loop and self._loop.is_running():
            self._loop.create_task(self._callback(msg))

    def handle(self, client: blcsdk.BlcPluginClient, command: dict):
        cmd = command.get('cmd')
        data = command.get('data', {})

        # Parse ExtraData using the SDK model for proper typing
        extra = sdk_models.ExtraData.from_dict(command.get('extra', {}))
        room_id = extra.room_id

        # Skip messages generated by other plugins to avoid duplicates
        if extra.is_from_plugin:
            return

        # Dump raw packet to log/messages/ for chat commands (skip heartbeats/system)
        if cmd in _CHAT_COMMANDS:
            _write_raw_message(command, room_id)
            logger.info('[SDK] RAW: %s', json.dumps(command, ensure_ascii=False))

        # Dispatch to specific processors
        if cmd == 50:
            self._process_add_text(data, room_id)
        elif cmd == 51:
            self._process_add_gift(data, room_id)
        elif cmd == 52:
            self._process_add_member(data, room_id)
        elif cmd == 53:
            self._process_add_super_chat(data, room_id)

    def _process_add_text(self, data, room_id: Optional[int]):
        # ADD_TEXT (cmd=50) sends data as a LIST on the blivechat wire protocol.
        # Use the SDK model's from_command() to parse the positional list correctly.
        try:
            msg_obj = sdk_models.AddTextMsg.from_command(data)
        except Exception as e:
            logger.warning(f'[SDK] Failed to parse ADD_TEXT data: {e}')
            return

        content = msg_obj.content
        author_name = msg_obj.author_name

        ts_dt = datetime.now()

        parsed = ParsedMessage(
            timestamp=ts_dt,
            type=MessageType.DM,
            username=author_name,
            content={"message": content},
            unique_id=f"{ts_dt.isoformat()}_{author_name}_dm"
        )
        self._safe_callback(parsed)

    def _process_add_gift(self, data: dict, room_id: Optional[int]):
        # AddGiftMsg: giftName, num, totalCoin, totalFreeCoin...
        total_coin = data.get('totalCoin', 0)
        is_paid = total_coin != 0
        
        msg_type = MessageType.PAID_GIFT if is_paid else MessageType.FREE_GIFT
        currency = '元' if is_paid else '银瓜子'
        value = (total_coin / 1000) if is_paid else data.get('totalFreeCoin', 0)
        
        author_name = data.get('authorName', '')
        gift_name = data.get('giftName', '')
        num = data.get('num', 0)
        
        ts_dt = datetime.now()
        type_suffix = 'paid_gift' if is_paid else 'free_gift'
        
        parsed = ParsedMessage(
            timestamp=ts_dt,
            type=msg_type,
            username=author_name,
            content={
                "gift_name": gift_name,
                "quantity": num,
                "value": value,
                "currency": currency
            },
            unique_id=f"{ts_dt.isoformat()}_{author_name}_{type_suffix}"
        )
        self._safe_callback(parsed)

    def _process_add_member(self, data: dict, room_id: Optional[int]):
        # AddMemberMsg: privilegeType 
        privilege_type = data.get('privilegeType', 0)
        guard_name = GUARD_LEVEL_NAMES.get(privilege_type, '未知舰队等级')
        
        total_coin = data.get('total_coin', 0)  # SDK wire uses snake_case 'total_coin' for AddMemberMsg
        value = total_coin / 1000
        
        webhook_type = None
        # GuardLevel: LV3=1 (总督/Governor), LV2=2 (提督/Admiral), LV1=3 (舰长/Captain)
        if privilege_type == 1: webhook_type = 'governor'
        elif privilege_type == 2: webhook_type = 'admiral'
        elif privilege_type == 3: webhook_type = 'captain'

        author_name = data.get('authorName', '')
        num = data.get('num', 0)
        
        ts_dt = datetime.now()
        tts_text = f"{author_name}。\t 非常感谢您的支持！"
        
        parsed = ParsedMessage(
            timestamp=ts_dt,
            type=MessageType.GUARD,
            username=author_name,
            content={
                "duration": num,
                "guard_type": guard_name,
                "value": value,
                "currency": "元"
            },
            tts_enabled=True,
            tts_text=tts_text,
            webhook_type=webhook_type,
            unique_id=f"{ts_dt.isoformat()}_{author_name}_guard_{webhook_type or 'unknown'}"
        )
        self._safe_callback(parsed)

    def _process_add_super_chat(self, data: dict, room_id: Optional[int]):
        # AddSuperChatMsg: price, content
        price = data.get('price', 0)
        content = data.get('content', '')
        author_name = data.get('authorName', '')
        
        ts_dt = datetime.now()
        
        parsed = ParsedMessage(
            timestamp=ts_dt,
            type=MessageType.SUPERCHAT,
            username=author_name,
            content={
                "amount": price,
                "message": content,
                "currency": "元"
            },
            tts_enabled=True,
            tts_text=f"{author_name}说: {content}",
            unique_id=f"{ts_dt.isoformat()}_{author_name}_sc"
        )
        self._safe_callback(parsed)
